### ISSUE TITLE
Lab description and tests do not align

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/angular-integrate-http-lab#2]
Lab readme asks for a getUser method that returns some data to the console with no mention of there needing to be a return value. Test does not check for anything in the console and is really just looking for an `$http.get()` call to the API. The test even take care of the following `.then()` call.

Lab readme also asks for an updateUser method that checks the `status` of a post to the API. Again, the test is just looking for a method that returns a `$http.post()` call to the API, and the test checks the status.

**Comment by aturkewi** [comment]
@PeterBell

**Comment by PeterBell** [comment]
Any suggested improvements @aturkewi ?

**Comment by AnnJohn** [comment]
closing because of PR
